### ISSUE TITLE
reqwest can not cross build for target x86_64-unknown-linux-musl with tokio library

### ISSUE THREAD

**Issue by ikey4u** [messense/cargo-zigbuild#11]
This a minimal example to reproduce the problem.

- Cargo.toml

      [package]
      name = "reqwest-demo"
      version = "0.1.0"
      edition = "2021"

      [dependencies]
      reqwest = { version = "0.11.9", features = ["json", "multipart", "native-tls-vendored"] }
      tokio = { version = "1.0", features = [ "full" ] }

- main.rs

      #[tokio::main]
      async fn main() {
          let response = reqwest::Client::new()
              .post("http://www.baidu.com")
              .form(&[("one", "1")])
              .send()
              .await
              .expect("send");
          println!("Response status {}", response.status());
      }

Notice that reqwest enables feature `native-tls-vendored` to let us build tls library source using zig. 

To build the example, using command below

    cargo-zigbuild zigbuild --target x86_64-unknown-linux-musl

The generated error is here

    ld.lld: error: undefined symbol: _$LT$libc..unix..linux_like..linux..musl..sigaction$u20$as$u20$core..clone..Clone$GT$::clone::h5d005990411f7b3b
          >>> referenced by lib.rs:196 (~/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/signal-hook-registry-1.4.0/src/lib.rs:196)
          >>>               signal_hook_registry-bdc7223cbb468750.signal_hook_registry.c6e8fee1-cgu.3.rcgu.o:(_$LT$signal_hook_registry..Prev$u20$as$u20$core..clone..Clone$GT$::clone::h3790061594f1b072)

And line 196 is [here](https://github.com/vorner/signal-hook/blob/d4bd2bab6fc8b65d5e0b917f8c248addaab51ebf/signal-hook-registry/src/lib.rs#L196)

**Comment by ikey4u** [comment]
I've updated the problem description, and if we can find the symbol in zig lib, then the problem is caused with the filter flags. Otherwise, it maybe a problem related with zig itself.

**Comment by messense** [comment]
@ikey4u Are you using Rust 1.59.0, please try #12.

**Comment by ikey4u** [comment]
@messense yes, I use rust 1.59.0, and the build passed using the pr #12

**Comment by ikey4u** [comment]
@messense Unfortunately, I test this patch with Rust 1.58.0, it does not work. The error is the same.

**Comment by messense** [comment]
That's unfortunate but this project is so young that I'm not aiming for supporting old Rust versions.

**Comment by ikey4u** [comment]
its does not matter, but you can specify the minimal supported rust version on homepage.

**Comment by messense** [comment]
For future reference, this issue is caused by upstream [Rust distributes libc.a in self-contained for musl and wasi since Rust 1.59.0](https://github.com/rust-lang/rust/pull/90527) (I think the code is in 1.58.0 but isn't really used since it requires a libc 0.2.107 and later).
