### ISSUE TITLE
is bash really required?

### ISSUE THREAD

**Issue by remissio** [messense/cargo-zigbuild#37]
hi :)

I am using cargo-zigbuild within my [container-image](https://gitlab.com/sbenv/veroxis/oci/-/blob/main/rust-zig-fat.Dockerfile) and i was wondering if using `sh` instead of `bash` would be a more platform-agnostic solution.

Aweome project! Thanks a lot for that!

**Comment by messense** [comment]
I think it's possible, let me give it a try.
