### ISSUE TITLE
Can a wrapper for `cargo run` be added, too?

### ISSUE THREAD

**Issue by kkysen** [messense/cargo-zigbuild#39]
It would be helpful if a wrapper for `cargo run` was added, like how `cargo zigbuild` wraps `cargo build`.  I'm running the cross-compiled binaries using qemu, and it would be a lot more seamless if something like `cargo zigbuild run` or `cargo zig run` worked.  Thanks!

**Comment by messense** [comment]
Here you go #40 , do you have a sample Cargo QEMU runner configuration that I can add to CI?

**Comment by kkysen** [comment]
Wow, that was fast!  Thank you!

For testing, I don't really have anything set up.  I was just doing this for testing on `arm-unknown-linux-gnueabihf`:
```sh
rustup target add arm-unknown-linux-gnueabihf
sudo apt install qemu-user qemu-user-static gcc-arm-linux-gnueabihf
sudo update-binfmts --enable qemu-arm
export QEMU_LD_PREFIX=/usr/arm-linux-gnueabihf
cargo-zigbuild run --target arm-unknown-linux-gnueabihf
```

**Comment by messense** [comment]
Thanks! Added qemu integration tests in #41.
