### ISSUE TITLE
paths with spaces or on a secondary drive

### ISSUE THREAD

**Issue by NathanSkilton** [messense/cargo-zigbuild#42]
I've discovered that I'm unable to build if the path contains spaces or is on a secondary drive.

When I run the following command in the following locations on Windows 10 x64:
cargo zigbuild --release --target aarch64-unknown-linux-gnu

- c:\HelloWorld builds fine

- c:\Hello World gets truncated:

`error: linking with C:\Users\User\AppData\Local\cargo-zigbuild\0.9.0\zigcc-aarch64-unknown-linux-gnu.bat failed: exit code: 1`

`warning: FileNotFound: C:\Hello`

- d:\HelloWorld gives renaming errors:

`warning: /usr/bin/ar: unable to rename 'd:\HelloWorld\target\aarch64-unknown-linux-gnu\release\build\ring-f728d5470a7d5974\out\libring-core.a'; reason: Invalid cross-device link`

`error: failed to run custom build command for ring v0.16.20`

**Comment by rtldg** [comment]
>`warning: /usr/bin/ar: unable to rename 'd:\HelloWorld\target\aarch64-unknown-linux-gnu\release\build\ring-f728d5470a7d5974\out\libring-core.a'; reason: Invalid cross-device link`

This might be caused by whatever is providing that `/usr/bin/ar`/`ar.exe`.

I ended up making a `zigar.bat` file with `zig ar --format=gnu %*` inside to be my `AR` environment variable and that seems to work fine with my `D:/` code folder builds.

**Comment by messense** [comment]
@rtldg Thanks for information, I guess we can add support for setting up `zig ar` and maybe also `zig ranlib` in `cargo-zigbuild` automatically.

**Comment by rtldg** [comment]
Worth mentioning that `zigar.bat` also runs into the command-line length limitation stuff from batch/cmd.exe (like when compiling libcurl or libgit2), so I've now wrapped calling `zig ar` with a `zigar.exe`
```
fn main() {
  let mut args: Vec<String> = std::env::args().collect();
  args[0] = "ar".into();
  let code = std::process::Command::new("zig")
    .args(args)
    .spawn()
    .expect("failed to spawn 'zig ar'")
    .wait()
    .expect("failed to wait on 'zig ar'")
    .code()
    .expect("failed to unwrap 'zig ar' exit code");
  std::process::exit(code);
}
```
I would've liked to just use `set AR=zig ar` but that doesn't really work since Windows tries to run `zig ar` + args instead of `zig` + `ar` + args

**Comment by messense** [comment]
> c:\Hello World gets truncated:
>
> error: linking with C:\Users\User\AppData\Local\cargo-zigbuild\0.9.0\zigcc-aarch64-unknown-linux-gnu.bat failed: exit code: 1
> warning: FileNotFound: C:\Hello

I can't reproduce this on Windows 11 using cargo-zigbuild 0.12.0.

<img width="919" alt="image" src="https://user-images.githubusercontent.com/1556054/183283188-bfb2f114-c794-4e9b-a1fe-f238d4cd253d.png">
