### ISSUE TITLE
Add `zig ar` and `zig ranlib` support

### ISSUE THREAD

**Issue by messense** [messense/cargo-zigbuild#52]
>`warning: /usr/bin/ar: unable to rename 'd:\HelloWorld\target\aarch64-unknown-linux-gnu\release\build\ring-f728d5470a7d5974\out\libring-core.a'; reason: Invalid cross-device link`

This might be caused by whatever is providing that `/usr/bin/ar`/`ar.exe`.

I ended up making a `zigar.bat` file with `zig ar --format=gnu %*` inside to be my `AR` environment variable and that seems to work fine with my `D:/` code folder builds.

_Originally posted by @rtldg in https://github.com/messense/cargo-zigbuild/issues/42#issuecomment-1205964597_

**Comment by messense** [comment]
@rtldg Please try [v0.12.0-beta.1](https://crates.io/crates/cargo-zigbuild/0.12.0-beta.1), if nothing goes wrong, I'll release v0.12.0 soon.

**Comment by rtldg** [comment]
It runs into the `The command line is too long.` issue because of .bat/batch/cmd.exe. 
I'll try to make a small example real quick to show

**Comment by rtldg** [comment]
The limit for batch/cmd.exe being like `8192` according to google.
Also, I assume that the program calling `AR` will automatically use the `@file-with-command-line-args.txt` thing when it is above/near the Windows limit (32767?), but my current project only has like 14000~ so I'm not sure

**Comment by rtldg** [comment]
`src/main.rs`
```
fn main() {
    println!("Hello, world!");
}
```
`Cargo.toml`
```
[package]
name = "testb"
version = "0.1.0"
edition = "2021"

[dependencies]
curl = { version = "0.4.33", default-features = false, features = ["rustls", "static-curl"] }
```
main errors:
```
cargo:warning=The command line is too long.
  exit code: 1

  --- stderr


  error occurred: Command "C:\\Users\\joe\\AppData\\Local\\cargo-zigbuild\\0.12.0-beta.1\\zigar.bat" "cq"
  /* ... little over 9000 (ha) characters here ... */
```
[build log.txt](https://github.com/messense/cargo-zigbuild/files/9274342/build.log.txt)

**Comment by rtldg** [comment]
I'm not sure how to deal with this besides compiling an .exe to avoid the [.bat 8192 (8191?) character limit](https://docs.microsoft.com/en-GB/troubleshoot/windows-client/shell-experience/command-line-string-limitation#examples)

**Comment by messense** [comment]
@rtldg Please give v0.12.0-beta.2 a try, it works on CI now.

**Comment by rtldg** [comment]
It fails unless you have admin-privileges due to [`std::os::windows::fs::symlink_file`](https://doc.rust-lang.org/std/os/windows/fs/fn.symlink_file.html) it seems.
`Error: A required privilege is not held by the client. (os error 1314)`

I was hoping that `std::fs::hard_link` could replace it but that then starts to run into issues with the `if target.exists() { fs::remove_file(target)?; }` since it can't delete the file since it's symlinked to the running .exe
```
Error: failed to remove file `C:\Users\joe\AppData\Local\cargo-zigbuild\0.12.0-beta.1\ar.exe`

Caused by:
    Access is denied. (os error 5)
```

Might just be easiest to copy the exe instead of symlinking on Windows.

**Comment by messense** [comment]
We don't really have to remove the symlink file since we already add version number in the cache directory path. Would `hard_link` then work for you?

**Comment by rtldg** [comment]
That's a good point. Yeah, that'd work

**Comment by messense** [comment]
@rtldg Can you try main branch?

**Comment by rtldg** [comment]
It seems to work fine now :)
