### ISSUE TITLE
Build i686-pc-windows-gnu failed

### ISSUE THREAD

**Issue by EddieIvan01** [messense/cargo-zigbuild#61]
When using cargo build i686-pc-windows-gnu, the architecture for zig should be i386-windows-gnu instead of i686-windows-gnu

```
> cargo zigbuild --target i686-pc-windows-gnu
...
error: UnknownArchitecture

> cat /Users/x/Library/Caches/cargo-zigbuild/0.12.2/zigcc-i686-pc-windows-gnu.sh
#!/usr/bin/env sh
/Users/x/.cargo/bin/cargo-zigbuild zig cc -- -target i686-windows-gnu -g $@
```

**Comment by messense** [comment]
Looks like even with `i386-windows-gnu` zig still fails to build: https://github.com/messense/cargo-zigbuild/actions/runs/3050875072/jobs/4918466906
